version: "3.8"

services:
  frontend:
    build:
      context: ./M5-frontend
    ports:
      - 3000:3000
    networks:
      - mission5

  backend:
    build:
      context: ./M5-backend
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      MONGDODB_URL: mongodb://database:27017
    networks:
      - mission5
    depends_on:
      - database
    links:
      - database

  database:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    networks:
      - mission5
    volumes:
      - mission5:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://database:27017
    networks:
      - mission5

networks:
  mission5:
    driver: bridge

volumes:
  mission5:
    driver: local
